### ISSUE TITLE
Eager loading data

### ISSUE THREAD

**Issue by noplanman** [jesperbjerke/laravel-api-query-builder#1]
Is there a way to use eager loading with this library?

For example, when selecting a single entity via API, it would be cool to eager load relationships instead or generating a duplicate query:
```php
// controller
public function show(Thing $thing): JsonResponse
{
    $thing->loadMissing('relation');

    return ThingResource::make($thing)->response();
}
```

As it is now, I need to do this:
```php
public function show(Thing $thing, Request $request): JsonResponse
{
    $thing = (new QueryBuilder($thing, $request))->build()->first();

    return ThingResource::make($thing)->response();
}
```

Seems a bit un-pretty 🤔 

---

**Update:**
My example above for showing a single entity didn't work, it always returned the first result of the new query.
This change did get me what I want, but it still uses the same code above in the controller.
```php
// in QueryBuilder::build()
$query = $this->model->exists
    ? $this->model->newQueryForRestoration($this->model)
    : $this->model->newQuery();
```

---

**Update 2:**
Something like this could work pretty well I think, adding an extra method to the trait (same for `loadCount`).
```php
// in QueryBuilderModelTrait
public function loadApiRelations(): self
{
    $with = collect(request('with'))
        ->map(fn($item) => explode(',', $item))
        ->flatten();

    return $this->loadMissing($this->validatedApiRelations($with));
}
```
Then it can be used as:
```php
// controller
public function show(Thing $thing): JsonResponse
{
    $thing->loadApiRelations();

    return ThingResource::make($thing)->response();
}
```

**Comment by jesperbjerke** [comment]
I am not sure I understand what you want to achieve. It looks like you already have a model fetched and then want to use the querybuilder on it? I don't see what the querybuilder would do for you in this case? 

Using the `with` keyword allows you to eagerload relations, just like in regular eloqouent: https://github.com/jesperbjerke/laravel-api-query-builder#with

**Comment by noplanman** [comment]
The problem with the `with` approach, is that it generates a new request (as far as I've understood).
So in my controller's `show` the model is already loaded, so instead of generating a new request with `with`, what makes sense to just `load` any extras if need be, via `$model->loadMissing`.

At the moment my solution is to extend the base `Model` class with a new `loadApiData` method, so `$model->loadApiData()` does that for me (relations and counts), using your `allowed*` methods to define which ones.

Hope that explains it a bit more.

**Comment by jesperbjerke** [comment]
This querybuilder just uses the regular Eloquent Builder under the hood, so it works just like Eloquent does when you call `with` on a query.

I still don't understand why you need this package's querybuilder if you already have fetched the model?

But whatever works for you :)
